name: default
channels:
- conda-forge
- nodefaults
dependencies:
- jupyter >=1.1.1,<2
- numpy >=2.5.2,<3
- matplotlib >=3.11.1,<4
- pdf2image >=1.17.0,<2
- pytesseract >=0.3.13,<0.4
- fastapi >=0.141.1,<0.142
- requests >=2.34.2,<3
- pillow >=12.3.0,<13
- opencv >=5.0.0,<6
- sentence-transformers >=6.0.1,<7
- chromadb >=1.5.9,<2
- ollama-python >=0.6.2,<0.7
- litellm >=1.99.0,<2
- pytest >=9.1.1,<10
- python >=3.11
- pip
- pip:
  - -e .
